usersprojL2/appbasic/urls.py
from django.urls import path
from appbasic import views

app_name = 'appbasic'
urlpatterns = [
    path('', views.registerView, name='register'),
    path('login/', views.loginView, name='login_site'),
]

usersprojL2/usersprojL2/urls.py
from django.contrib import admin
from django.urls import path, include
from appbasic import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.indexView, name='index'),
    path('register/', include('appbasic.urls')),
    path('logout/', views.logoutView, name='logout_site'),
    path('special/', views.specialView, name='special'),
]

usersprojL2/appbasic/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics_dir', blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

usersprojL2/appbasic/forms.py
from django import forms
from django.contrib.auth.models import User
from appbasic.models import UserProfileModel


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileModel
        fields = ('portfolio_site', 'profile_pic')

usersprojL2/appbasic/views.py
from django.shortcuts import render
from appbasic.forms import UserForm, UserProfileInfoForm

# imports for login
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse

# Create your views here.


def indexView(request):
    return render(request, 'appbasic/index.html')


@login_required
def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def specialView(request):
    return HttpResponse('You are in')


def registerView(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and user_profile_form.is_valid():
            user = user_form.save(commit=True)
            user.set_password(user.password)
            user.save()

            profile = user_profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print("Picture detected")
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True

    else:
        user_form = UserForm()
        user_profile_form = UserProfileInfoForm()

    data_dict = {'registered': registered, 'user_form': user_form,
                 'user_profile_form': user_profile_form}
    return render(request, 'appbasic/register.html', context=data_dict)


# The login view
def loginView(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user, backend=None)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account is not active')
        else:
            print('Someone tried to login and failed')
            print("Username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, 'appbasic/login.html')

usersprojL2/templates/appbasic/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <ul class="nav navbar">
          <li><a class="navbar-brand" href="{% url 'index'%}">Home</a> </li>
          <li><a class="nav-link" href="{% url 'admin:index'%}">Admin</a> </li>
          <li><a class="nav-link" href="{% url 'appbasic:register'%}">Register</a> </li>

          {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'logout_site'%}">Logout</a> </li>
            {% else %}
              <li><a class="nav-link" href="{% url 'appbasic:login_site'%}">Login</a> </li>

          {% endif %}

        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      <!-- Anything outside of this will be inherited if you extend! -->
      {% endblock %}
    </div>


  </body>
  </html>

usersprojL2/templates/appbasic/index.html
<!DOCTYPE html>
{% extends 'appbasic/base.html'%}
{% block body_block%}
  <h1>Home Page</h1>
{% endblock %}

usersprojL2/templates/appbasic/login.html
<!DOCTYPE html>
{% extends 'appbasic/base.html'%}
{% block body_block%}
  <h1>Login Page</h1>
  <div class="jumbotron">
    <form action="{% url 'appbasic:login_site' %}" method="post">
      {% csrf_token %}
      <label for="username"> Username </label>
      <input type="username" name="username" placeholder="Enter a Username">

      <label for="password"> Password </label>
      <input type="password" name="password">
      <input class="btn btn-primary" type="submit" value="Submit">
    </form>
  </div>
{% endblock %}

usersprojL2/templates/appbasic/register.html
<!DOCTYPE html>
{% extends 'appbasic/base.html'%}
{% block body_block%}
  <h1>Registration Page</h1>
  <div class="jumbotron">
    {% if registered %}
      <h2>Thank you for registering</h2>
      {% else %}
        <form enctype="multipart/form-data" method="post">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ user_profile_form.as_p}}
          <input type="submit" value="Register">
        </form>

    {% endif %}

  </div>

{% endblock %}